import "./globals.css";
import { ViewTransitions } from "next-view-transitions";

import ReactLenis from "@studio-freight/react-lenis";

import Nav from "./components/nav";
import Footer from "./components/footer";

export const metadata = {
  title: "Devansh Ohri, Designer",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ViewTransitions>
    <html lang="en">
      <body>
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
    </ViewTransitions>
  );
}
